### ISSUE TITLE
Add support for specifying multiple keys per datacenter

### ISSUE THREAD

**Issue by jessfs** [jaxxstorm/locksmith#18]
Hi! We'd love to use this project in our environment, but our security model requires at least a certain threshold of keys (higher than just 1). Would you consider adding support for specifying multiple GPG encrypted unseal keys per datacenter?

**Comment by jaxxstorm** [comment]
Hi @jessfs 
Yes I absolutely want to support this. I am trying to find time in my schedule to add this support, but in the meantime, a PR would be much appreciated.

**Comment by ljagiello** [comment]
Hi @jaxxstorm 

https://github.com/jaxxstorm/hookpick/pull/19 should add support for multiple keys (I hope I tested all possible cases for multiple keys)
