### ISSUE TITLE
cannot find package "github.com/jaxxstorm/hookpick/cmd"

### ISSUE THREAD

**Issue by emcniece** [jaxxstorm/locksmith#20]
Hey, just trying to build & test this neat looking tool! Following the README and got stuck at the build step:

```sh
cd $GOPATH/src
git clone https://github.com/jaxxstorm/hookpick.git
cd hookpick
curl https://glide.sh/get | sh
glide
go build -o hookpick main.go

    main.go:23:8: cannot find package "github.com/jaxxstorm/hookpick/cmd" in any of:
	[GOPATH]/src/hookpick/vendor/github.com/jaxxstorm/hookpick/cmd (vendor tree)
	[GOROOT]/src/github.com/jaxxstorm/hookpick/cmd (from $GOROOT)
	[GOPATH]/src/github.com/jaxxstorm/hookpick/cmd (from $GOPATH)
```

This is because `main.go` imports `github.com/jaxxstorm/hookpick/cmd` and not `./cmd`, right? Should I be building with a different command?

Side note, `make build` fails too because I don't have `goxc` installed, this will be the next issue to solve.

**Comment by jaxxstorm** [comment]
It's because your git clone isn't right. Try this:

```
mkdir -p $GOPATH/src/github.com/jaxxstorm
cd $GOPATH/src/github.com/jaxxstorm
git clone https://github.com/jaxxstorm/hookpick.git
```

and go from there

**Comment by jaxxstorm** [comment]
I opened #21 to fix the goxc thing, bear with me

**Comment by emcniece** [comment]
No sweat dude - thanks for the fast response!

Directory moving worked like a charm, thanks so much 🎉
